// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHU8_Yq6Fp_Q-7Vt62cgl-_KiwLmBjHWg',
    appId: '1:287204114808:web:6534f47704d9935619c88d',
    messagingSenderId: '287204114808',
    projectId: 'fir-21312027',
    authDomain: 'fir-21312027.firebaseapp.com',
    storageBucket: 'fir-21312027.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZk9Huq8oCcpZAdxgVr-rkEFlLisp7m68',
    appId: '1:287204114808:android:e50f2d50a4375bed19c88d',
    messagingSenderId: '287204114808',
    projectId: 'fir-21312027',
    storageBucket: 'fir-21312027.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe6a2l7bP1z8ynCdtrWnWGSS8Amnlnai4',
    appId: '1:287204114808:ios:342d6d6b08ced32b19c88d',
    messagingSenderId: '287204114808',
    projectId: 'fir-21312027',
    storageBucket: 'fir-21312027.appspot.com',
    iosClientId: '287204114808-6bnc8lngn1fqia30am7d2877524cq45e.apps.googleusercontent.com',
    iosBundleId: 'com.ifgabsp.projectGet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe6a2l7bP1z8ynCdtrWnWGSS8Amnlnai4',
    appId: '1:287204114808:ios:f3d668b669850b1319c88d',
    messagingSenderId: '287204114808',
    projectId: 'fir-21312027',
    storageBucket: 'fir-21312027.appspot.com',
    iosClientId: '287204114808-4n9gb3um2c4j94rv3db8u705r81ciga0.apps.googleusercontent.com',
    iosBundleId: 'com.ifgabsp.projectGet.RunnerTests',
  );
}
